import Head from "next/head";
import { useState, useEffect } from "react";
import style from "../styles/Home.module.css";
import VideosList from "../Components/VideosList";
import { useVideos } from "../hooks/useVideos";

export default function Home () {
    const [inputValue, setInputValue] = useState({
        title: "",
        link: ""
    });

    const { error, loading, data } = useVideos();

    const [videoArray, setVideoArray] = useState([]);

    useEffect(() => {
        if (videoArray.length == 0 && data) {
            setVideoArray(prevValue => {
                return [...videoArray, ...data.allVideos];
            });
        }
    }, [loading]);

    const handleSubmit = e => {
        e.preventDefault();

        if (inputValue.title && inputValue.link) {
            let taskObject = {
                id: videoArray.length,
                title: inputValue.title,
                link: `https://www.youtube.com/embed/${inputValue.link}`
            };

            setVideoArray(prevValue => {
                return [...videoArray, taskObject];
            });

            setInputValue(prevValue => {
                return { ...inputValue, title: "", link: "" };
            });
        }
    };

    return (
        <>
            <div className={style.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta name='description' content='Generated by create next app' />
                    <link rel='icon' href='/favicon.ico' />
                </Head>

                <main className={style.main}>
                    <h2>Video Management</h2>

                    <VideosList
                        videoArray={videoArray}
                        setVideoArray={setVideoArray}
                        data={data}
                        loading={loading}
                        error={error}
                        inputValue={inputValue}
                        setInputValue={setInputValue}
                        handleSubmit={handleSubmit}
                    ></VideosList>
                </main>
            </div>
        </>
    );
}
